ALTER TABLE %PREFIX%trades
ADD COLUMN `trade_id` INT NOT NULL AUTO_INCREMENT,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`trade_id`),
ADD UNIQUE INDEX `trade_id_UNIQUE` (`trade_id` ASC);

ALTER TABLE %PREFIX%trades
ADD COLUMN `planet_id` INT(11) NULL DEFAULT NULL,
ADD COLUMN `trade_fleet_array` TEXT NULL DEFAULT NULL,
CHANGE COLUMN `seller_fleet_id` `seller_fleet_id` BIGINT(11) UNSIGNED NULL DEFAULT '0' ,
ADD COLUMN `resource_metal` DOUBLE(50,0) NULL,
ADD COLUMN `resource_crystal` DOUBLE(50,0) NULL,
ADD COLUMN `resource_deuterium` DOUBLE(50,0) NULL,
ADD COLUMN  `closed` TINYINT(4) NULL DEFAULT '0',
DROP PRIMARY KEY;
